=== expkg-zone58/ex-schematron/examples/ark/ark.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.schematron.info/ark" xmlns="http://www.schematron.info/ark" elementFormDefault="qualified">
  <xs:element name="age" type="xs:positiveInteger"/>
  <xs:element name="ark">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="load"/>
        <xs:element ref="maxReproductionAge"/>
        <xs:element ref="loadingCapacity"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="species" type="xs:string"/>
  <xs:element name="weight" type="xs:positiveInteger"/>
  <xs:element name="load">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="room" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="maxReproductionAge">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="animal_species" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="male" type="xs:positiveInteger"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="loadingCapacity" type="xs:positiveInteger"/>
  <xs:element name="animal">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="species"/>
        <xs:element ref="weight"/>
        <xs:element ref="age"/>
      </xs:sequence>
      <xs:attribute name="sex" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="male"/>
            <xs:enumeration value="female"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="carnivore" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="animal_species">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="male"/>
        <xs:element ref="female"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="room">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="animal" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="female" type="xs:positiveInteger"/>
</xs:schema>

=== expkg-zone58/ex-schematron/examples/ark/ark.xml
<?xml version="1.0" encoding="UTF-8"?>
<ark xmlns="http://www.schematron.info/ark" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.schematron.info/ark ark.xsd">
  <load>
    <room>
      <animal sex="female" carnivore="no">
        <species>zebra</species>
        <weight>200</weight>
        <age>12</age>
      </animal>
      <animal sex="male" carnivore="no">
        <species>zebra</species>
        <weight>250</weight>
        <age>13</age>
      </animal>
    </room>
    <room>
      <animal sex="female" carnivore="yes">
        <species>lion</species>
        <weight>200</weight>
        <age>23</age>
      </animal>
      <animal sex="male" carnivore="yes">
        <species>lion</species>
        <weight>180</weight>
        <age>30</age>
      </animal>
    </room>
    <room>
      <animal sex="female" carnivore="no">
        <species>elephant</species>
        <weight>10000</weight>
        <age>20</age>
      </animal>
      <animal sex="male" carnivore="no">
        <species>elephant</species>
        <weight>15000</weight>
        <age>40</age>
      </animal>
    </room>
  </load>
  <maxReproductionAge>
    <animal_species>
      <name>elephant</name>
      <male>80</male>
      <female>30</female>
    </animal_species>
    <animal_species>
      <name>lion</name>
      <male>30</male>
      <female>15</female>
    </animal_species>
    <animal_species>
      <name>zebra</name>
      <male>30</male>
      <female>20</female>
    </animal_species>
  </maxReproductionAge>
  <loadingCapacity>44000</loadingCapacity>
</ark>
